# Generated by Django 4.0.5 on 2022-06-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
