# Generated by Django 4.0.5 on 2022-06-07 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_comment_user_alter_comment_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='likes',
            field=models.ManyToManyField(related_name='bet', to=settings.AUTH_USER_MODEL),
        ),
    ]
